//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `RSSIStatus.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __RSSIStatus_h__
#define __RSSIStatus_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompRSSIStatus
{

class RSSIStatus;
class RSSIStatusPrx;

}

namespace RoboCompRSSIStatus
{

class HardwareFailedException : public ::Ice::UserExceptionHelper<HardwareFailedException, ::Ice::UserException>
{
public:

    virtual ~HardwareFailedException();

    HardwareFailedException(const HardwareFailedException&) = default;

    HardwareFailedException() = default;

    /**
     * One-shot constructor to initialize all data members.
     */
    HardwareFailedException(const ::std::string& what) :
        what(::std::move(what))
    {
    }

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&> ice_tuple() const
    {
        return std::tie(what);
    }

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    ::std::string what;
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

struct TRSSI
{
    float percentage;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const float&> ice_tuple() const
    {
        return std::tie(percentage);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompRSSIStatus
{

class RSSIStatus : public virtual ::Ice::Object
{
public:

    using ProxyType = RSSIStatusPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual TRSSI getRSSIState(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getRSSIState(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompRSSIStatus
{

class RSSIStatusPrx : public virtual ::Ice::Proxy<RSSIStatusPrx, ::Ice::ObjectPrx>
{
public:

    TRSSI getRSSIState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::RoboCompRSSIStatus::TRSSI>(true, this, &RSSIStatusPrx::_iceI_getRSSIState, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getRSSIStateAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompRSSIStatus::TRSSI>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompRSSIStatus::TRSSI, P>(false, this, &RSSIStatusPrx::_iceI_getRSSIState, context);
    }

    ::std::function<void()>
    getRSSIStateAsync(::std::function<void(::RoboCompRSSIStatus::TRSSI)> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompRSSIStatus::TRSSI>(response, ex, sent, this, &RoboCompRSSIStatus::RSSIStatusPrx::_iceI_getRSSIState, context);
    }

    /// \cond INTERNAL
    void _iceI_getRSSIState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompRSSIStatus::TRSSI>>&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    RSSIStatusPrx() = default;
    friend ::std::shared_ptr<RSSIStatusPrx> IceInternal::createProxy<RSSIStatusPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<typename S>
struct StreamReader<::RoboCompRSSIStatus::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompRSSIStatus::HardwareFailedException& v)
    {
        istr->readAll(v.what);
    }
};

template<>
struct StreamableTraits<::RoboCompRSSIStatus::TRSSI>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 4;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamReader<::RoboCompRSSIStatus::TRSSI, S>
{
    static void read(S* istr, ::RoboCompRSSIStatus::TRSSI& v)
    {
        istr->readAll(v.percentage);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompRSSIStatus
{

using RSSIStatusPtr = ::std::shared_ptr<RSSIStatus>;
using RSSIStatusPrxPtr = ::std::shared_ptr<RSSIStatusPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompRSSIStatus
{

class RSSIStatus;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< RSSIStatus>&);
::IceProxy::Ice::Object* upCast(RSSIStatus*);
/// \endcond

}

}

namespace RoboCompRSSIStatus
{

class RSSIStatus;
/// \cond INTERNAL
::Ice::Object* upCast(RSSIStatus*);
/// \endcond
typedef ::IceInternal::Handle< RSSIStatus> RSSIStatusPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompRSSIStatus::RSSIStatus> RSSIStatusPrx;
typedef RSSIStatusPrx RSSIStatusPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(RSSIStatusPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompRSSIStatus
{

class HardwareFailedException : public ::Ice::UserException
{
public:

    HardwareFailedException() {}
    /**
     * One-shot constructor to initialize all data members.
     */
    explicit HardwareFailedException(const ::std::string& what);
    virtual ~HardwareFailedException() throw();

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    virtual ::std::string ice_id() const;
    /**
     * Polymporphically clones this exception.
     * @return A shallow copy of this exception.
     */
    virtual HardwareFailedException* ice_clone() const;
    /**
     * Throws this exception.
     */
    virtual void ice_throw() const;

    ::std::string what;

protected:

    /// \cond STREAM
    virtual void _writeImpl(::Ice::OutputStream*) const;
    virtual void _readImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

struct TRSSI
{
    ::Ice::Float percentage;
};

}

namespace RoboCompRSSIStatus
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompRSSIStatus::RSSIStatus::begin_getRSSIState.
 * Create a wrapper instance by calling ::RoboCompRSSIStatus::newCallback_RSSIStatus_getRSSIState.
 */
class Callback_RSSIStatus_getRSSIState_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RSSIStatus_getRSSIState_Base> Callback_RSSIStatus_getRSSIStatePtr;

}

namespace IceProxy
{

namespace RoboCompRSSIStatus
{

class RSSIStatus : public virtual ::Ice::Proxy<RSSIStatus, ::IceProxy::Ice::Object>
{
public:

    ::RoboCompRSSIStatus::TRSSI getRSSIState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getRSSIState(_iceI_begin_getRSSIState(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getRSSIState(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getRSSIState(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getRSSIState(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getRSSIState(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getRSSIState(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getRSSIState(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getRSSIState(const ::RoboCompRSSIStatus::Callback_RSSIStatus_getRSSIStatePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getRSSIState(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getRSSIState(const ::Ice::Context& context, const ::RoboCompRSSIStatus::Callback_RSSIStatus_getRSSIStatePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getRSSIState(context, cb, cookie);
    }

    ::RoboCompRSSIStatus::TRSSI end_getRSSIState(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getRSSIState(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompRSSIStatus
{

class RSSIStatus : public virtual ::Ice::Object
{
public:

    typedef RSSIStatusPrx ProxyType;
    typedef RSSIStatusPtr PointerType;

    virtual ~RSSIStatus();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual TRSSI getRSSIState(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getRSSIState(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const RSSIStatus& lhs, const RSSIStatus& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const RSSIStatus& lhs, const RSSIStatus& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompRSSIStatus::HardwareFailedException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<typename S>
struct StreamWriter< ::RoboCompRSSIStatus::HardwareFailedException, S>
{
    static void write(S* ostr, const ::RoboCompRSSIStatus::HardwareFailedException& v)
    {
        ostr->write(v.what);
    }
};

template<typename S>
struct StreamReader< ::RoboCompRSSIStatus::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompRSSIStatus::HardwareFailedException& v)
    {
        istr->read(v.what);
    }
};

template<>
struct StreamableTraits< ::RoboCompRSSIStatus::TRSSI>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 4;
    static const bool fixedLength = true;
};

template<typename S>
struct StreamWriter< ::RoboCompRSSIStatus::TRSSI, S>
{
    static void write(S* ostr, const ::RoboCompRSSIStatus::TRSSI& v)
    {
        ostr->write(v.percentage);
    }
};

template<typename S>
struct StreamReader< ::RoboCompRSSIStatus::TRSSI, S>
{
    static void read(S* istr, ::RoboCompRSSIStatus::TRSSI& v)
    {
        istr->read(v.percentage);
    }
};

}
/// \endcond

namespace RoboCompRSSIStatus
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompRSSIStatus::RSSIStatus::begin_getRSSIState.
 * Create a wrapper instance by calling ::RoboCompRSSIStatus::newCallback_RSSIStatus_getRSSIState.
 */
template<class T>
class CallbackNC_RSSIStatus_getRSSIState : public Callback_RSSIStatus_getRSSIState_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const TRSSI&);

    CallbackNC_RSSIStatus_getRSSIState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        RSSIStatusPrx proxy = RSSIStatusPrx::uncheckedCast(result->getProxy());
        TRSSI ret;
        try
        {
            ret = proxy->end_getRSSIState(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompRSSIStatus::RSSIStatus::begin_getRSSIState.
 */
template<class T> Callback_RSSIStatus_getRSSIStatePtr
newCallback_RSSIStatus_getRSSIState(const IceUtil::Handle<T>& instance, void (T::*cb)(const TRSSI&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RSSIStatus_getRSSIState<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompRSSIStatus::RSSIStatus::begin_getRSSIState.
 */
template<class T> Callback_RSSIStatus_getRSSIStatePtr
newCallback_RSSIStatus_getRSSIState(T* instance, void (T::*cb)(const TRSSI&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RSSIStatus_getRSSIState<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompRSSIStatus::RSSIStatus::begin_getRSSIState.
 * Create a wrapper instance by calling ::RoboCompRSSIStatus::newCallback_RSSIStatus_getRSSIState.
 */
template<class T, typename CT>
class Callback_RSSIStatus_getRSSIState : public Callback_RSSIStatus_getRSSIState_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const TRSSI&, const CT&);

    Callback_RSSIStatus_getRSSIState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        RSSIStatusPrx proxy = RSSIStatusPrx::uncheckedCast(result->getProxy());
        TRSSI ret;
        try
        {
            ret = proxy->end_getRSSIState(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompRSSIStatus::RSSIStatus::begin_getRSSIState.
 */
template<class T, typename CT> Callback_RSSIStatus_getRSSIStatePtr
newCallback_RSSIStatus_getRSSIState(const IceUtil::Handle<T>& instance, void (T::*cb)(const TRSSI&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RSSIStatus_getRSSIState<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompRSSIStatus::RSSIStatus::begin_getRSSIState.
 */
template<class T, typename CT> Callback_RSSIStatus_getRSSIStatePtr
newCallback_RSSIStatus_getRSSIState(T* instance, void (T::*cb)(const TRSSI&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RSSIStatus_getRSSIState<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
