name: "Docker Image"

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  robocomp-dsr-components:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: robocomp/robocomp
          tags: |
            type=ref, suffix=__dsr_components__latest, event=branch
            type=sha, prefix={{branch}}__dsr_components__

      - uses: docker/setup-buildx-action@v1
        id: dsr-components-builder

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build against dsr-components-builder
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.dsr-builder.outputs.name }}
          context: docker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:  |
            branch=${{ steps.extract_branch.outputs.branch }}


